name: Release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1          
      - uses: olafurpg/setup-gpg@v3
      - uses: peaceiris/actions-hugo@v2.4.13
        with: 
          hugo-version: '0.89.4'
          extended: true      
      - run: sbt -J-Xmx3000m versionCheck ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: website
        run: |
          sbt clean +docs/mdoc +docs/unidoc
          cd website
          hugo
          cd public
          touch .nojekyll
      - name: gh-pages-deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./website/public
